repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: check-yaml
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: mixed-line-ending
      - id: name-tests-test
      - id: trailing-whitespace
  - repo: https://github.com/psf/black
    rev: 25.9.0
    hooks:
      - id: black
  - repo: https://github.com/csachs/pyproject-flake8
    rev: v7.0.0
    hooks:
      - id: pyproject-flake8
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.18.2
    hooks:
      - id: mypy
        additional_dependencies:
          - "aiohttp"
          - "sqlalchemy"
          - "sqlmodel"
          - "types-aiofiles"
          - "types-requests"
        exclude: "^examples/"
  - repo: https://github.com/pycqa/isort
    rev: 7.0.0
    hooks:
      - id: isort
  - repo: https://github.com/PyCQA/bandit
    rev: 1.8.6
    hooks:
      - id: bandit
